---
# tasks file for istio mesh networking

- name: Show facts available on the system
  ansible.builtin.debug:
    var: ansible_facts
  when: ingress_display_facts == "yes"

##################
# istio mesh networking specific
##################

#- name: Set firewall rules for ingress trafics on CentOS/Redhat/Rocky-Linux
#  firewalld:
#    zone: public
#    port: "{{ item }}"
#    permanent: yes
#    immediate: yes
#    state: enabled
#  loop:
#    # For ingress trafics via ingress controllers 
#    - 80/tcp
#    - 443/tcp
#  notify:
#    - reload firewalld
#  when: ((ansible_facts['os_family']|lower == 'redhat') or (ansible_facts['os_family']|lower == 'rocky')) and (inventory_hostname in groups['k8sworkernodes']) and (centos_mesh_implementation == "istio")

