---
# vars file for k8s gatewayapi-crds 
#
######################################################
# Common variables
#
# If one wants to display the ansible facts while running the playbook, set the following variable to "yes"
ingress_gwapi_version: "{{ global_gwapi_version }}"
ingress_display_facts: "{{ global_display_facts }}"
#
# End of common varibles
######################################################
######################################################
# CentOS specific
#
centos_gwapi_crdurl: "https://github.com/kubernetes-sigs/gateway-api/releases/download/{{ingress_gwapi_version}}/standard-install.yaml"
centos_gwapi_expcrdurl: "https://github.com/kubernetes-sigs/gateway-api/releases/download/{{ingress_gwapi_version}}/experimental-install.yaml"
# End of CentOS specific
######################################################

######################################################
# Ubuntu specific
#
#
# End of Ubuntu specific
######################################################

